## *Pandas Task*

In [2]:
import pandas as pd

In [7]:
df=pd.read_csv("C:/GEN_AI/Dummy/dummy2.csv")
df.to_csv("C:/GEN_AI/Dummy/dummy3.csv",index=False)
df

,Car_Name,Brand,Year,Price,Fuel_Type,Transmission,Mileage,Seats
0,Swift,Maruti Suzuki,2022,"₹7,50,000",Petrol,Manual,22.0,5
1,Creta,Hyundai,2023,"₹14,00,000",Diesel,Automatic,18.0,5
2,Nexon,Tata,2024,"₹12,50,000",Petrol,Manual,17.5,5
3,Innova,Toyota,2022,"₹22,00,000",Diesel,Automatic,15.0,7
4,City,Honda,2021,"₹12,00,000",Petrol,Automatic,17.8,5
5,Thar,Mahindra,2024,"₹18,00,000",Diesel,Manual,15.2,4
6,Punch,Tata,2023,"₹8,00,000",Petrol,Manual,20.0,5
7,Fortuner,Toyota,2024,"₹42,00,000",Diesel,Automatic,10.0,7
8,Baleno,Maruti Suzuki,2022,"₹8,50,000",Petrol,Manual,22.5,5
9,Seltos,Kia,2023,"₹15,00,000",Diesel,Automatic,18.0,5

In [8]:
df["Price"]=df["Price"].apply(lambda x:float(x[1:].replace(',','')))
df

,Car_Name,Brand,Year,Price,Fuel_Type,Transmission,Mileage,Seats
0,Swift,Maruti Suzuki,2022,750000.0,Petrol,Manual,22.0,5
1,Creta,Hyundai,2023,1400000.0,Diesel,Automatic,18.0,5
2,Nexon,Tata,2024,1250000.0,Petrol,Manual,17.5,5
3,Innova,Toyota,2022,2200000.0,Diesel,Automatic,15.0,7
4,City,Honda,2021,1200000.0,Petrol,Automatic,17.8,5
5,Thar,Mahindra,2024,1800000.0,Diesel,Manual,15.2,4
6,Punch,Tata,2023,800000.0,Petrol,Manual,20.0,5
7,Fortuner,Toyota,2024,4200000.0,Diesel,Automatic,10.0,7
8,Baleno,Maruti Suzuki,2022,850000.0,Petrol,Manual,22.5,5
9,Seltos,Kia,2023,1500000.0,Diesel,Automatic,18.0,5

In [9]:
df1 = df[df["Price"] <= 10000000]
df1

,Car_Name,Brand,Year,Price,Fuel_Type,Transmission,Mileage,Seats
0,Swift,Maruti Suzuki,2022,750000.0,Petrol,Manual,22.0,5
1,Creta,Hyundai,2023,1400000.0,Diesel,Automatic,18.0,5
2,Nexon,Tata,2024,1250000.0,Petrol,Manual,17.5,5
3,Innova,Toyota,2022,2200000.0,Diesel,Automatic,15.0,7
4,City,Honda,2021,1200000.0,Petrol,Automatic,17.8,5
5,Thar,Mahindra,2024,1800000.0,Diesel,Manual,15.2,4
6,Punch,Tata,2023,800000.0,Petrol,Manual,20.0,5
7,Fortuner,Toyota,2024,4200000.0,Diesel,Automatic,10.0,7
8,Baleno,Maruti Suzuki,2022,850000.0,Petrol,Manual,22.5,5
9,Seltos,Kia,2023,1500000.0,Diesel,Automatic,18.0,5

In [10]:
df3 = df1[(df1["Brand"] == "Toyota") & (df1["Price"] <= 10000000)]
df3

   Car_Name   Brand  Year      Price Fuel_Type Transmission  Mileage  Seats
3    Innova  Toyota  2022  2200000.0    Diesel    Automatic     15.0      7
7  Fortuner  Toyota  2024  4200000.0    Diesel    Automatic     10.0      7