## *Python Pandas*

In [1]:
import pandas as pd

## *Pandas Series*

In [3]:
price = pd.Series([10, 20, 30, 40])
print(price)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
print(price.dtype)
print(price.shape)
print(price.size)

int64
(4,)
4

In [5]:
print(price[0])

10

In [13]:
price = pd.Series([10000000, 20000000, 30000000, 4000000000], index=['a', 'b', 'c', 'd'])
print(price)

a      10000000
b      20000000
c      30000000
d    4000000000
dtype: int64

In [14]:
print(price['a'])

10000000

In [17]:
carname = pd.Series(['Dodge','Ferrari','Bugatti','BMW'],index = ['a', 'b', 'c', 'd'])
print(carname)

a      Dodge
b    Ferrari
c    Bugatti
d        BMW
dtype: str

In [18]:
data = {
    "Car": carname,
    "Price": price
}

df = pd.DataFrame(data)
print(df)

       Car       Price
a    Dodge    10000000
b  Ferrari    20000000
c  Bugatti    30000000
d      BMW  4000000000

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Mark    3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [28]:
data = {
    "Name": ["Ram", "Sam", "Ravi"],
    "Age": [20, 21, 19],
    "Mark": [85, 90, 78]
}

df = pd.DataFrame(data)
df

   Name  Age  Mark
0   Ram   20    85
1   Sam   21    90
2  Ravi   19    78

In [22]:
df=pd.read_csv("C:/GEN_AI/Dummy/dummy2.csv")
df

,Car_Name,Brand,Year,Price_Lakhs,Fuel_Type,Transmission,Mileage,Seats
0,Swift,Maruti Suzuki,2022,7.5,Petrol,Manual,22.0,5
1,Creta,Hyundai,2023,14.0,Diesel,Automatic,18.0,5
2,Nexon,Tata,2024,12.5,Petrol,Manual,17.5,5
3,Innova,Toyota,2022,22.0,Diesel,Automatic,15.0,7
4,City,Honda,2021,12.0,Petrol,Automatic,17.8,5
5,Thar,Mahindra,2024,18.0,Diesel,Manual,15.2,4
6,Punch,Tata,2023,8.0,Petrol,Manual,20.0,5
7,Fortuner,Toyota,2024,42.0,Diesel,Automatic,10.0,7
8,Baleno,Maruti Suzuki,2022,8.5,Petrol,Manual,22.5,5
9,Seltos,Kia,2023,15.0,Diesel,Automatic,18.0,5

In [25]:
df.to_csv("C:/GEN_AI/Dummy/dummy3.csv",index=False)

In [27]:
df1=pd.read_csv("C:/GEN_AI/Dummy/dummy3.csv")
df1

,Car_Name,Brand,Year,Price_Lakhs,Fuel_Type,Transmission,Mileage,Seats
0,Swift,Maruti Suzuki,2022,7.5,Petrol,Manual,22.0,5
1,Creta,Hyundai,2023,14.0,Diesel,Automatic,18.0,5
2,Nexon,Tata,2024,12.5,Petrol,Manual,17.5,5
3,Innova,Toyota,2022,22.0,Diesel,Automatic,15.0,7
4,City,Honda,2021,12.0,Petrol,Automatic,17.8,5
5,Thar,Mahindra,2024,18.0,Diesel,Manual,15.2,4
6,Punch,Tata,2023,8.0,Petrol,Manual,20.0,5
7,Fortuner,Toyota,2024,42.0,Diesel,Automatic,10.0,7
8,Baleno,Maruti Suzuki,2022,8.5,Petrol,Manual,22.5,5
9,Seltos,Kia,2023,15.0,Diesel,Automatic,18.0,5

In [30]:
df1.dtypes

Car_Name            str
Brand               str
Year              int64
Price_Lakhs     float64
Fuel_Type           str
Transmission        str
Mileage         float64
Seats             int64
dtype: object

In [31]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car_Name      10 non-null     str
 1   Brand         10 non-null     str
 2   Year          10 non-null     int64
 3   Price_Lakhs   10 non-null     float64
 4   Fuel_Type     10 non-null     str
 5   Transmission  10 non-null     str
 6   Mileage       10 non-null     float64
 7   Seats         10 non-null     int64
dtypes: float64(2), int64(2), str(4)
memory usage: 772.0 bytes

In [33]:
df1.isnull().sum()

Car_Name        0
Brand           0
Year            0
Price_Lakhs     0
Fuel_Type       0
Transmission    0
Mileage         0
Seats           0
dtype: int64

In [34]:
df1.notnull().sum()

Car_Name        10
Brand           10
Year            10
Price_Lakhs     10
Fuel_Type       10
Transmission    10
Mileage         10
Seats           10
dtype: int64

In [35]:
df1.describe()

              Year  Price_Lakhs    Mileage      Seats
count    10.000000    10.000000  10.000000  10.000000
mean   2022.800000    15.950000  17.600000   5.300000
std       1.032796    10.229179   3.648135   0.948683
min    2021.000000     7.500000  10.000000   4.000000
25%    2022.000000     9.375000  15.775000   5.000000
50%    2023.000000    13.250000  17.900000   5.000000
75%    2023.750000    17.250000  19.500000   5.000000
max    2024.000000    42.000000  22.500000   7.000000

In [36]:
df1.head()

,Car_Name,Brand,Year,Price_Lakhs,Fuel_Type,Transmission,Mileage,Seats
0,Swift,Maruti Suzuki,2022,7.5,Petrol,Manual,22.0,5
1,Creta,Hyundai,2023,14.0,Diesel,Automatic,18.0,5
2,Nexon,Tata,2024,12.5,Petrol,Manual,17.5,5
3,Innova,Toyota,2022,22.0,Diesel,Automatic,15.0,7
4,City,Honda,2021,12.0,Petrol,Automatic,17.8,5

In [38]:
df1.tail()

,Car_Name,Brand,Year,Price_Lakhs,Fuel_Type,Transmission,Mileage,Seats
5,Thar,Mahindra,2024,18.0,Diesel,Manual,15.2,4
6,Punch,Tata,2023,8.0,Petrol,Manual,20.0,5
7,Fortuner,Toyota,2024,42.0,Diesel,Automatic,10.0,7
8,Baleno,Maruti Suzuki,2022,8.5,Petrol,Manual,22.5,5
9,Seltos,Kia,2023,15.0,Diesel,Automatic,18.0,5

In [40]:
df.head(2)

  Name  Age  Mark
0  Ram   20    85
1  Sam   21    90

## loc and iloc

In [51]:
df1.loc[1:22]

,Car_Name,Brand,Year,Price_Lakhs,Fuel_Type,Transmission,Mileage,Seats
1,Creta,Hyundai,2023,14.0,Diesel,Automatic,18.0,5
2,Nexon,Tata,2024,12.5,Petrol,Manual,17.5,5
3,Innova,Toyota,2022,22.0,Diesel,Automatic,15.0,7
4,City,Honda,2021,12.0,Petrol,Automatic,17.8,5
5,Thar,Mahindra,2024,18.0,Diesel,Manual,15.2,4
6,Punch,Tata,2023,8.0,Petrol,Manual,20.0,5
7,Fortuner,Toyota,2024,42.0,Diesel,Automatic,10.0,7
8,Baleno,Maruti Suzuki,2022,8.5,Petrol,Manual,22.5,5
9,Seltos,Kia,2023,15.0,Diesel,Automatic,18.0,5

In [43]:
df1.iloc[3:5]

  Car_Name   Brand  Year  Price_Lakhs Fuel_Type Transmission  Mileage  Seats
3   Innova  Toyota  2022         22.0    Diesel    Automatic     15.0      7
4     City   Honda  2021         12.0    Petrol    Automatic     17.8      5

In [48]:
df1.iloc[7::]

,Car_Name,Brand,Year,Price_Lakhs,Fuel_Type,Transmission,Mileage,Seats
7,Fortuner,Toyota,2024,42.0,Diesel,Automatic,10.0,7
8,Baleno,Maruti Suzuki,2022,8.5,Petrol,Manual,22.5,5
9,Seltos,Kia,2023,15.0,Diesel,Automatic,18.0,5

In [52]:
df1

,Car_Name,Brand,Year,Price_Lakhs,Fuel_Type,Transmission,Mileage,Seats
0,Swift,Maruti Suzuki,2022,7.5,Petrol,Manual,22.0,5
1,Creta,Hyundai,2023,14.0,Diesel,Automatic,18.0,5
2,Nexon,Tata,2024,12.5,Petrol,Manual,17.5,5
3,Innova,Toyota,2022,22.0,Diesel,Automatic,15.0,7
4,City,Honda,2021,12.0,Petrol,Automatic,17.8,5
5,Thar,Mahindra,2024,18.0,Diesel,Manual,15.2,4
6,Punch,Tata,2023,8.0,Petrol,Manual,20.0,5
7,Fortuner,Toyota,2024,42.0,Diesel,Automatic,10.0,7
8,Baleno,Maruti Suzuki,2022,8.5,Petrol,Manual,22.5,5
9,Seltos,Kia,2023,15.0,Diesel,Automatic,18.0,5

## colums

In [55]:
df1.Brand

0    Maruti Suzuki
1          Hyundai
2             Tata
3           Toyota
4            Honda
5         Mahindra
6             Tata
7           Toyota
8    Maruti Suzuki
9              Kia
Name: Brand, dtype: str

In [57]:
df1["Brand"].value_counts()

Brand
Maruti Suzuki    2
Tata             2
Toyota           2
Hyundai          1
Honda            1
Mahindra         1
Kia              1
Name: count, dtype: int64

In [58]:
df1[df1["Brand"]=="Tata"]

  Car_Name Brand  Year  Price_Lakhs Fuel_Type Transmission  Mileage  Seats
2    Nexon  Tata  2024         12.5    Petrol       Manual     17.5      5
6    Punch  Tata  2023          8.0    Petrol       Manual     20.0      5

### *Pivot table* (Comparing two colums)

pd.crosstab(df1["Brand"],df1[""])